### ISSUE TITLE
Leaving the Github Organization

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/meta#2]
Hi everyone, I'm leaving this Github Organization because I want to focus on other things. 🙂 

I think that the [Community Map](https://github.com/WeAreFairphone/fprsmap) has reached a well and mature state, also after great contributions by @Ingo-FP-Angel. Our latest project, the [Fairphone Angels Homepage](https://github.com/WeAreFairphone/fpangels-hp), has received new features from @ff2u quickly after my initial commit. So I'm not leaving everything deserted. 😉 

I'll be around if you have any questions and you can find me at the [forum](https://forum.fairphone.com/). 😄

Happy sharing! 💙 
Best, Stefan

**Comment by ff2u** [comment]
I'm sorry to see you go and I'm very grateful for all you've done here! 
I wish you all the best for the new things you're planning to focus on! :-)

**Comment by Roboe** [comment]
You did an amazing work here.

Farewell, friend! Good luck with your "other things", :hugs:

**Comment by Ingo-FP-Angel** [comment]
Of course it's sad to see you go, but all the best with whatever those other things are! Maybe we can welcome you back at some point in the future.

Is there any organizational stuff we need to take care of now? Repo ownerships, CI access or the like?

**Comment by StefanBrand** [comment]
I think you can access the CI too, right? 

In any case, contact the admins/owners of the organization if something doesn't work as expected. 😊


-- 
Diese Nachricht wurde von meinem Fairphone mit K-9 Mail gesendet.

Am 13. Dezember 2019 18:05:58 MEZ schrieb Ingo-FP-Angel <notifications@github.com>:
>Of course it's sad to see you go, but all the best with whatever those
>other things are! Maybe we can welcome you back at some point in the
>future.
>
>Is there any organizational stuff we need to take care of now? Repo
>ownerships, CI access or the like?

**Comment by Ingo-FP-Angel** [comment]
If I know the address (https://travis-ci.org/wearefairphone) I can open it with my browser. But organization membership doesn't work for me with Travis, even with my own Github Repos.

And currently the builds for the map and homepage fail
https://travis-ci.org/WeAreFairphone/fprsmap/builds/625147490
https://travis-ci.org/WeAreFairphone/fpangels-hp/builds/625083818

Both bail out with "Couldn't push the build to github.com/WeAreFairphone/XYZ.git:gh-pages"

**Comment by ff2u** [comment]
> And currently the builds for the map and homepage fail
> https://travis-ci.org/WeAreFairphone/fprsmap/builds/625147490
> https://travis-ci.org/WeAreFairphone/fpangels-hp/builds/625083818
> 
> Both bail out with "Couldn't push the build to github.com/WeAreFairphone/XYZ.git:gh-pages"

I assume this is - since 4 days - a problem with the secure token (GITHUB_TOKEN) to access the according two WeAreFairphone repositories. But I can't check or try to fix that as I assume I don't have the necessary rights (I can't access the settings of the repositories).

**Comment by StefanBrand** [comment]
Let's bundle discussion here:
https://github.com/WeAreFairphone/fpangels-hp/issues/10#issuecomment-566166026
